name: material_color_picker
description: Color picker for Flutter.
version: 0.0.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # test: ^0.12.0

flutter:
  assets:
    - res/images/placer.png

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"